name: expandable_overlay
description: An overlay that expands from the button that's used to open it and then collapses back into it
version: 0.0.2
homepage: https://github.com/VKBobyr/expandable-overlay

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
