name: tester
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

expandable_overlay:
  path: ../

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  expandable_overlay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #
